// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

package frc.robot.subsystems;

import frc.robot.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import edu.wpi.first.wpilibj.drive.KilloughDrive;
import edu.wpi.first.wpilibj.motorcontrol.MotorControllerGroup;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class Drivetrain extends SubsystemBase {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
private WPI_TalonSRX talonSRX1;
private WPI_TalonSRX talonSRX2;
private MotorControllerGroup motorControllerGroup1;
private WPI_TalonSRX talonSRX3;
private WPI_TalonSRX talonSRX4;
private MotorControllerGroup motorControllerGroup2;
private WPI_TalonSRX talonSRX5;
private WPI_TalonSRX talonSRX6;
private MotorControllerGroup motorControllerGroup3;
private KilloughDrive killoughDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    /**
    *
    */
    public Drivetrain() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
talonSRX1 = new WPI_TalonSRX(0);
 
 

talonSRX2 = new WPI_TalonSRX(1);
 
 

motorControllerGroup1 = new MotorControllerGroup(talonSRX1, talonSRX2  );
 addChild("Motor Controller Group 1",motorControllerGroup1);
 

talonSRX3 = new WPI_TalonSRX(2);
 
 

talonSRX4 = new WPI_TalonSRX(3);
 
 

motorControllerGroup2 = new MotorControllerGroup(talonSRX3, talonSRX4  );
 addChild("Motor Controller Group 2",motorControllerGroup2);
 

talonSRX5 = new WPI_TalonSRX(4);
 
 

talonSRX6 = new WPI_TalonSRX(5);
 
 

motorControllerGroup3 = new MotorControllerGroup(talonSRX5, talonSRX6  );
 addChild("Motor Controller Group 3",motorControllerGroup3);
 

killoughDrive = new KilloughDrive(motorControllerGroup1, motorControllerGroup2,
motorControllerGroup3);
 addChild("Killough Drive",killoughDrive);
 killoughDrive.setSafetyEnabled(true);
killoughDrive.setExpiration(0.1);
killoughDrive.setMaxOutput(1.0);



    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    @Override
    public void periodic() {
        // This method will be called once per scheduler run

    }

    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void drive(double yAxis, double xAxis, double rotation) {
        killoughDrive.driveCartesian(yAxis, xAxis, rotation);
    }

}
